# Generated by Django 2.1.3 on 2018-11-22 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryControl', '0003_auto_20181122_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='Item Value',
            new_name='item_value',
        ),
    ]
