# Generated by Django 2.1.3 on 2018-11-21 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('purchase_date', models.DateField(verbose_name='Date of Purchase')),
                ('delivery_date', models.DateField(verbose_name='Date of Delivery')),
                ('Item Value', models.DecimalField(decimal_places=3, max_digits=99, verbose_name='Value of Item')),
                ('storage_location', models.CharField(max_length=1000)),
                ('estimated_life', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=200)),
                ('org_created', models.DateField(verbose_name='Date of Organization Creation')),
                ('info_budget', models.BooleanField(verbose_name='Was an informational budget submitted?')),
            ],
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField(verbose_name='Date of Sanction Application')),
                ('sanction_duration', models.DurationField()),
                ('sanction_type', models.CharField(max_length=1500)),
                ('offense_description', models.CharField(max_length=10000)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pantomath.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pantomath.Organization'),
        ),
    ]
