# Generated by Django 2.1.3 on 2018-11-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pantomath', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_mission',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='estimated_life',
            field=models.DurationField(help_text='This is entered in DD HH:MM:SS'),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='sanction_duration',
            field=models.DurationField(help_text='This is entered in DD HH:MM:SS'),
        ),
    ]
