# Generated by Django 2.1.3 on 2018-11-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pantomath', '0002_auto_20181121_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='Item Value',
            field=models.DecimalField(decimal_places=3, max_digits=20, verbose_name='Value of Item'),
        ),
    ]
